# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: mixed-line-ending
- repo: local
  hooks:
  - id: codegen
    name: codegen
    pass_filenames: false
    always_run: true
    language: system
    entry: >
      sh -c 'make codegen && git add Formula/*.rb'
